name: react_ci_workflow

on: 
  [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops_project:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops_project:latest

      - name: Set Kubernetes Context
        run: |
          kubectl config set-cluster minikube --server=https://85fe-209-141-167-194.ngrok-free.app --certificate-authority=~/.minikube/ca.crt
          kubectl config set-credentials minikube --token=''
          kubectl config set-context minikube --cluster=minikube --user=minikube
          kubectl config use-context minikube
          
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./deployment.yaml --validate=false
          kubectl apply -f ./service.yaml --validate=false
